language: python

python:
  - 3.7

# Whitelist branches
branches:
  only:
    - master

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt -i https://test.pypi.org/simple/ 
  - python setup.py install --force

# Run tests
script:
  - py.test tests/
